name: Compile, test and check the docs

on:
  workflow_call: 

jobs:

  test:
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: 9.2.1
            ghc-options: ""
          - ghc: latest

    runs-on: ubuntu-latest

    steps:

      - uses: nikita-volkov/build-and-test-cabal-package.github-action@v1
        with:
          ghc: ${{matrix.ghc}}
          ghc-options: ${{matrix.ghc-options}}
